[package]
name = "shared"
version = "0.1.0"
authors = ["jd68770 <josematias.misiego@kbc.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.arduino-uno]
git = "https://github.com/Rahix/avr-hal"
rev = "536c5d"
